..\..\bin\elac.exe prelude.ela -c -nologo
..\..\bin\elac.exe char.ela -c -nologo
..\..\bin\elac.exe core.ela -c -nologo
..\..\bin\elac.exe generic.ela -c -nologo
..\..\bin\elac.exe list.ela -c -nologo
..\..\bin\elac.exe number.ela -c -nologo
..\..\bin\elac.exe random.ela -c -nologo
..\..\bin\elac.exe record.ela -c -nologo
..\..\bin\elac.exe reflect.ela -c -nologo
..\..\bin\elac.exe string.ela -c -nologo
..\..\bin\elac.exe tuple.ela -c -nologo
